replicaCount: 1
name: sql-db
image:
  repository: mysql
  tag: 5.7
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3306

mysql:
  username: haha
  password: gotcha

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi