apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 3306
  selector:
    app: {{ .Values.name }}
  type: {{ .Values.service.type }}