name: Terraform Validate on PR to Dev

on:
  pull_request:
    branches:
      - dev

jobs:
  terraform:
    name: Terraform Validate
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.1.0

      - name: Format Terraform files
        run: |
          cd tf-code
          terraform fmt -check

      - name: Terraform Init
        run: |
          cd tf-code
          terraform init    
      
      - name: Terraform Validate
        run: |
          cd tf-code
          terraform validate        
